//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Item
{
	public virtual int ItemId
	{
		get;
		set;
	}

	public virtual string ItemName
	{
		get;
		set;
	}

	public virtual int StdVolume
	{
		get;
		set;
	}

	public virtual string StdUnit
	{
		get;
		set;
	}

}

