//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ListItem
{
	public virtual int Amount
	{
		get;
		set;
	}

	public virtual int Volume
	{
		get;
		set;
	}

	public virtual string Unit
	{
		get;
		set;
	}

	public virtual List List
	{
		get;
		set;
	}

	public virtual Item Item
	{
		get;
		set;
	}

}

