//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class List
{
    public int ListId { get; set; }
    public string ListName { get; set; }

    public List()
    {
    }

    public List(string listName)
    {
        ListName = listName;
    }
}

