// <auto-generated />
namespace SmartFridge_WebDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangednullableDateTimetoDateTimeinmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangednullableDateTimetoDateTimeinmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201505251053166_Changed nullable DateTime to DateTime in models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
