--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Mar 05 2015 17:45
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'ItemList'   
--
DROP TABLE ListItem
GO
--
-- Drop Table    : 'Item'   
--
DROP TABLE Item
GO
--
-- Drop Table    : 'List'   
--
DROP TABLE List
GO
