//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SmartFridge_WebApplication.Models
{ 

public class Item
{
    public int ItemId { get; set; }
    public string ItemName { get; set; }
    public int StdVolume { get; set; }
    public string StdUnit { get; set; }

    public Item()
    {
    }

    public Item(string itemName, int stdVolume, string stdUnit)
    {
        ItemName = itemName;
        StdVolume = stdVolume;
        StdUnit = stdUnit;
    }
}
}
